# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: astral-sh.ruff
PackageVersion: 0.16.10
PackageLocale: en-US
Publisher: Astral
PublisherUrl: https://github.com/astral-sh
# PublisherSupportUrl:
# PrivacyUrl:
# Author:
PackageName: Ruff
# PackageUrl:
License: MIT
LicenseUrl: https://github.com/astral-sh/ruff/blob/HEAD/LICENSE
# Copyright:
# CopyrightUrl:
ShortDescription: An extremely fast Python linter, written in Rust.
# Description:
# Moniker:
Tags:
- linter
- pep8
- python
- python3
- ruff
- rust
- rustpython
- static-analysis
- static-code-analysis
- styleguide
- style-guide
ReleaseNotes: |-
  Released on 2026-10-01.

  Preview features
  - Add a migration guide for categories (#28087)
  - [pyupgrade] Add rule for context manager iterator annotations (UP052) (#29000)

  Performance
  - Reduce memory used by diagnostics (#28951)

  Server
  - Avoid running `uv format` in untrusted workspaces (#28873)

  Documentation
  - Fix links to moved changelog sections and renamed mdtests (#28941)
  - Add Python 3.15 as a supported version (#28907)
  - Add ty as a type checker example (#28906)

  Other changes
  - Update Rust toolchain to 1.99 and MSRV to 1.97 (#29047)
ReleaseNotesUrl: https://github.com/astral-sh/ruff/releases/tag/0.16.10
# PurchaseUrl:
# InstallationNotes:
# Documentations:
ManifestType: defaultLocale
ManifestVersion: 1.12.0
